apiVersion: apps/v1 
kind: Deployment 
metadata: 
 name: nginx-deployment 
spec: 
  replicas: 10
  selector:
    matchLabels:
      app: nginx-deploy
  template:
    metadata:
      name: nginx-pod
      labels: 
        app: nginx-deploy
    spec: 
      containers:
        - name: nginx 
          image: nginx 
          ports: 
           - containerPort: 8080

---
apiVersion: v1 
kind: Service 
metadata: 
 name: nginx-service 
spec: 
  selector:
    app: nginx-deploy
  type: ClusterIP
  ports: 
  - port: 80
    targetPort: 8080
    protocol: TCP

