# apiVersion: v1 
# kind: ConfigMap 
# metadata: 
#   name: mysql-config 
# data: 
#   my.cnf: | 
#     [mysqld]
#     datatdir=/var/lib/mysql 
#     socket=/var/run/mysqld/mysqld.sock 

apiVersion: v1
kind: ConfigMap 
metadata: 
  name: mysql-config
data: 
  my.cnf: |
    [mysqld]
    datadir=/var/lib/mysql
    socket=/var/run/mysqld/mysqld.sock