apiVersion: v1 
kind: Secret 
metadata: 
  name: mongo-secret 
type: Opaque
data: 
  mongo_root_user: YWRtaW4=   # Base64 encoded value for "admin"
  mongo_root_password: cGFzc3dvcmQxMjM=  # Base64 encoded value for "password123"
  mongo_web_user: bW9uZ29fZXhwcmVzc19hZG1pbg==  # Base64 encoded value for "mongo_express_admin"
  mongo_web_password: cGFzc3dvcmQxMjM= # Base64 encoded value for "password123"