apiVersion: v1 
kind: ResourceQuota 
metadata: 
  name: devopsteams-quota
  namespace: devopsteam
spec: 
  hard: 
    requests.cpu: "1" # 1 cpu = 1000 Milli cores
    requests.memory: "1Gi" # 1Gi = 1000 Mebibytes
    limits.cpu: "2"
    limits.memory: "2Gi"
    pods: "10"