apiVersion: apps/v1 
kind: Deployment 
metadata: 
 name: nginx-deployment 
spec: 
  replicas: 10
  selector:
    matchLabels:
      app: my_app
  template:
    metadata:
      name: nginx-pod
      labels: 
        app: my_app
    spec: 
      containers:
        - name: nginx 
          image: nginx 
          ports: 
           - containerPort: 8080
        
